### ISSUE TITLE
pci.cpp spelling correction: Unkown, Unknown

### ISSUE THREAD

**Issue by grahamperrin** [Dr-Noob/gpufetch#22]
https://github.com/Dr-Noob/gpufetch/pull/21 intended to fix a typo that originated in two places: 

https://github.com/Dr-Noob/gpufetch/commit/a397eb398e95eade1ebbe3cab7394f302084c321#diff-b52e39c94a6052ba322bd29245cba0cf7fbe55ae881900245fc886eaba0f5f5fR11

https://github.com/Dr-Noob/gpufetch/commit/a397eb398e95eade1ebbe3cab7394f302084c321#diff-8d90022bc2916457a50021b9cc669857bea6f47dbc917cf0b1cc8bacaef951a1R11

**Comment by Dr-Noob** [comment]
Thanks, good catch! I'll fix that in a future commit.

**Comment by Dr-Noob** [comment]
Typo fixed, closing.

**Comment by grahamperrin** [comment]
Thanks!
