### ISSUE TITLE
gpufetch does not detect the GPU

### ISSUE THREAD

**Issue by zohnannor** [Dr-Noob/gpufetch#24]
> If there is a NVIDIA GPU or Intel iGPU in the system and the appropiate backend is enabled but gpufetch does not detect the GPU, please create a new issue with the provided error message (in the gpufetch output) on the issues page.

```
$ gpufetch
[ERROR]: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
[ERROR]: No GPU was detected! Available GPUs are:
- GPU 0:
  * Vendor: NVIDIA
  * PCI id: 10de:0640
Please, make sure that the appropiate backend is enabled:
- CUDA backend:  ON
- Intel backend: ON
Visit https://github.com/Dr-Noob/gpufetch#2-backends for more information
$ lspci -nn | grep VGA
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation G96C [GeForce 9500 GT] [10de:0640] (rev a1)
```

**Comment by Dr-Noob** [comment]
Hey,

So this is not a gpufetch issue, but an issue in your CUDA installation. It means that [the CUDA driver is older than the CUDA library](https://www.cs.cmu.edu/afs/cs/academic/class/15668-s11/www/cuda-doc/html/group__CUDART__TYPES_g3f51e3575c2178246db0a94a430e0038.html). It doesn't have anything to do with gpufetch. Try to run another CUDA program and you'll see this error as well.

**Comment by zohnannor** [comment]
Ah well. Sorry for the issue. I guess my GPU is too old, I have trouble installing any drivers for it. Thanks for the tip though

**Comment by Dr-Noob** [comment]
Actually if you could manage to get the drivers working, gpufetch would not work because [your GPU has compute capability 1.1](https://www.techpowerup.com/gpu-specs/geforce-9500-gt.c3373) but [the minimum required by gpufetch is 2.0](https://github.com/Dr-Noob/gpufetch#1-support).

Supporting old GPUs is hard, but if you solve the issue with your drivers I would consider adding support for your GPU, given the fact that we could test the patches. It's hard to find such old hardware nowadays! That's why I didn't add support for compute capabilities lower than 2.0.

**Comment by zohnannor** [comment]
Well, I solved the problem with my drivers (installed correct package and configured Xorg), but the issue with CUDA persists, same outputs as in the original post. Not sure we can take much out of this situation now, or could we?

> if you solve the issue with your drivers I would consider adding support for your GPU

If you want it -- I would help you by trying new patches and reporting how things work (although the question is, do we *really need* to support such an ancient GPUs? I am about to switch to something more modern within half a year).

**Comment by Dr-Noob** [comment]
What I mean is that if you manage to have the drivers working I could try adding support for old GPUs. Seems like [the newest CUDA version that supports your GPU is CUDA 6.5](https://en.wikipedia.org/wiki/CUDA#GPUs_supported). I would say that a good way to know if drivers are installed properly is by issuing the `nvidia-smi` command. If it gives you the model of your GPU and other info, it should be working.

> the question is, do we really need to support such an ancient GPUs?

I don't see the need to support very old GPUs but sounds fun.
