### ISSUE TITLE
Weird cuda error prevents gpufetch from working 

### ISSUE THREAD

**Issue by gaming128** [Dr-Noob/gpufetch#27]
```
[gaming123@gamingmachine ~]$ gpufetch
[ERROR]: cudaErrorUnknown: unknown error
[ERROR]: No GPU was detected! Available GPUs are:
- GPU 0:
  * Vendor: NVIDIA
  * PCI id: 10de:2520
- GPU 1:
  * Vendor: AMD
  * PCI id: 1002:1638
Please, make sure that the appropiate backend is enabled:
- CUDA backend:  ON
- Intel backend: ON
```

**Comment by Dr-Noob** [comment]
As far as I can see, you are using an Ampere GPU, more specifically, the GA106 chip. To make any CUDA program work with your GPU, [you need CUDA >= 11.1](https://en.wikipedia.org/wiki/CUDA#GPUs_supported).

**Comment by gaming128** [comment]
> As far as I can see, you are using an Ampere GPU, more specifically, the GA106 chip. To make any CUDA program work with your GPU, [you need CUDA >= 11.1](https://en.wikipedia.org/wiki/CUDA#GPUs_supported).

I already have that according to nvidia-smi so...

**Comment by gaming128** [comment]
ok looks like the issue is 1st option so i reinstalled cuda, thanks for that
