### ISSUE TITLE
[ERROR]: Unknown CUDA device id: 0x2487

### ISSUE THREAD

**Issue by matteodev8** [Dr-Noob/gpufetch#28]
I am getting this error when running `gpufetch` (Btw the error says "Unkown", so there is a typo)

![image](https://user-images.githubusercontent.com/59450459/195977491-b27454db-1a63-44c5-b060-a0ba53cbfe58.png)

I am using a NVIDIA RTX 3060 (`01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060] [10de:2487] (rev a1)`)

**Comment by Dr-Noob** [comment]
Thanks for the notice.

I have updated the project and added your GPU chip. I'm closing the issue, feel free to reopen it if it does not work with the new commit, or if shows incorrect info.

PS: I see that the memory type is not detected correctly. I should take a look at that later on.
