### ISSUE TITLE
Add Raspberry Pi support

### ISSUE THREAD

**Issue by hmsjy2017** [Dr-Noob/gpufetch#3]
Since the GPU of the Raspberry Pi is VideoCore instead of NVIDIA, CUDA cannot be installed.

**Comment by Dr-Noob** [comment]
At the moment, gpufetch works only on NVIDIA GPUs (thus needing CUDA to work). The next GPUs to be supported will probably be Intel iGPUs, and after that, AMD GPUs (if I can get access to any of them with a ROCm environment working). This will eventually happen, but I don't think it will be soon. After those GPUs, I don't know which ones I will include (if I decide to add more). 

The thing is that support for ARM GPUs is (to the best of my knowledge) near impossible (RPi uses an ARM GPU). Right now, I would say that I will never add support for ARM GPUs, but time may change my mind. I would appreciate any pointer to learn how to implement so, but it looks like it's pretty hard (there are no libraries like CUDA for ARM GPUs, nor OS support to get any information...). 

Closing the issue.
