### ISSUE TITLE
`build.sh` broken

### ISSUE THREAD

**Issue by rongou** [Dr-Noob/gpufetch#32]
On ubuntu 22.04, running `./build.sh` produces some errors:
```console
./build.sh: 10: [: unexpected operator
...
./build.sh: 32: [: Linux==: unexpected operator
./build.sh: 34: [: Linux: unexpected operator
```
Looks like the `sh` version only supports single equal signs.

**Comment by Dr-Noob** [comment]
Thanks for the issue. 

Yes, in Ubuntu 22.04, `sh` is pointing to `dash`, rather than `bash`. I have fixed it in 9837236, closing.
