### ISSUE TITLE
Can't detect my gpu [nvidia]

### ISSUE THREAD

**Issue by DemwE** [Dr-Noob/gpufetch#35]
![Screenshot_2023-01-29-12-04-10_4480x1440](https://user-images.githubusercontent.com/91313779/215321997-cce38941-9b0f-4720-bc31-202dcb6c23f8.png)

**Comment by DemwE** [comment]
cuda location on arch
```/opt/cuda```
command for build
```cmake -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc -DCMAKE_CUDA_COMPILER_TOOLKIT_ROOT=/opt/cuda```

**Comment by Dr-Noob** [comment]
I've been installing this without specifying the CUDA location explicitly but looks like it doesn't work now. So I have updated the [gpufetch-git](https://aur.archlinux.org/packages/gpufetch-git) package to reflect this, thanks.
