### ISSUE TITLE
The package from aur is not being built (Arch Linux)

### ISSUE THREAD

**Issue by RazuvaevDD** [Dr-Noob/gpufetch#4]
![image](https://user-images.githubusercontent.com/15276724/132999955-2b2ed4ab-341e-460d-b91a-dc5bc0ac69b8.png)
(I'm writing because your Upstream URL is listed here: https://aur.archlinux.org/packages/gpufetch-git/)
![image](https://user-images.githubusercontent.com/15276724/133000023-e6700e93-8a67-464f-81af-6104702a70a6.png)

**Comment by Dr-Noob** [comment]
Thanks for the warning. I knew that it was failing, but I just didn't have the time to fix it. I just did so, closing the issue.
