### ISSUE TITLE
[ERROR]: Unknown Intel device id: 0x3EA0

### ISSUE THREAD

**Issue by archisman-panigrahi** [Dr-Noob/gpufetch#42]
I got the error message
```
[ERROR]: Unknown Intel device id: 0x3EA0
```

My processor is [ Intel® Core™ i5-8265U](https://www.intel.com/content/www/us/en/products/sku/149088/intel-core-i58265u-processor-6m-cache-up-to-3-90-ghz/specifications.html)

**Comment by Dr-Noob** [comment]
Thanks for reporting! Should work now, just update your main branch.

**Comment by archisman-panigrahi** [comment]
I verified that it works.
