### ISSUE TITLE
Intel Pentium G3420 igpu won't work w/ gpufetch

### ISSUE THREAD

**Issue by XeonBionic** [Dr-Noob/gpufetch#6]
``sh
[ERROR]: Unkown Intel device id: 0x0402
Please, create a new issue with this error message on https://github.com/Dr-Noob/gpufetch/issues
[ERROR]: No GPU was detected, or the detected GPU is not supported by gpufetch
Please, make sure that the appropiate backend is enabled:
- CUDA backend:  OFF
- Intel backend: ON
Visit https://github.com/Dr-Noob/gpufetch#2-backends for more information``

**Comment by Dr-Noob** [comment]
Thanks for the report!

I just updated the program. Give it a try, it should work now.
